branch 2 - test updated

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -4,32 +4,33 @@
 name: Test
 
 on:
-  workflow_run:       #run Test only if Train completes
+  workflow_run:
     workflows: ["Train"]
     types:
-      - completed 
- 
+      - completed
+      - requested
+
 jobs:
   pull-and-run:
     runs-on: ubuntu-latest
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
-      - name: Check out the code
-        uses: actions/checkout@v2
+      - name: Check if Train workflow was successful
+        id: check_train_status
+        run: |
+          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
+            echo "Train workflow did not succeed. Forcing Test workflow to fail."
+            exit 1
+          fi
 
       - name: Pull Docker image
         run: docker pull krpushpam/assignment_3:latest
 
       - name: Run Docker image and check score
-        id: test
         run: |
-          SCORE=$(docker run --rm  krpushpam/assignment_3:latest)
+          SCORE=$(docker run --rm krpushpam/assignment_3:latest)
           echo "Score: $SCORE"
-          if (( $(echo "$SCORE > 0.30" | bc -l) )); then
-            echo "Success: Score is greater than 0.30"
-            echo "::set-output name=passed::true"
+          if (( $(echo "$SCORE > 0.50" | bc -l) )); then
+            echo "Success: Score is greater than 0.50"
           else
-            echo "Failure: Score is not greater than 0.30"
-            echo "::set-output name=passed::false"
+            echo "Failure: Score is not greater than 0.50"
             exit 1
-          fi
